name: smart_call_scheduler
description: "An app to schedule calls to your loved ones and yourself"
publish_to: 'none'

version: 1.0.1+8

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  google_fonts: ^4.0.4
  http: ^0.13.3
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.2
  # flutter_sound: ^9.3.1  # Replaced with record and just_audio
  record: ^5.0.4  # Modern audio recording
  just_audio: ^0.9.36  # Modern audio playback
  path_provider: ^2.0.11
  path: ^1.8.0
  permission_handler: ^11.0.1
  audioplayers: ^6.1.0
  uuid: ^4.5.0
  intl: ^0.19.0
  flutter_slidable: ^3.1.1
  flutter_datetime_picker_plus: ^2.2.0
  device_info_plus: ^10.1.2
  flutter_timezone: ^3.0.1
  flutter_contacts: ^1.1.9
  timezone: ^0.9.4
  phone_number: ^2.1.0
  country_picker: ^2.0.26
  firebase_messaging: ^15.1.2
  firebase_core: ^3.6.0
  in_app_purchase: ^3.0.6
  shared_preferences: ^2.3.2
  introduction_screen: ^3.1.14
  flutter_launcher_icons: ^0.9.2
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon1.png
    - assets/images/reminders_icon.png
    - assets/images/call_logs_icon.png
    - assets/images/custom_mic_icon.png
    - assets/images/custom_stop_icon.png
    - assets/icons/reminders_icon.png
    - assets/icons/call_logs_icon.png
    - assets/icons/reminders_icon.svg
    - assets/icons/call_logs_icon.svg
    - assets/icons/audio_play_icon.png
    - assets/icons/play_icon.svg
    - assets/icons/pause_icon.svg
    - assets/images/empty_reminders_icon.png
    - assets/images/voice_reminders.png
    - assets/images/notifications.png